### ISSUE TITLE
`svg` helper for Ruby templates

### ISSUE THREAD

**Issue by jaredcwhite** [andrewmcodes/bridgetown-inline-svg#18]
I was able to around this by using `liquid_render` and a separate Liquid component to call the `svg` tag, but it'd be awesome to have a helper that works out-of-the-box with ERB. 😃

**Comment by andrewmcodes** [comment]
This has been on my list for awhile and I just haven't gotten to it yet so I'll bump the priority up.

**Comment by andrewmcodes** [comment]
Closing in favor of [ayushn21/bridgetown-svg-inliner](https://github.com/ayushn21/bridgetown-svg-inliner). This plugin works with the latest Bridgetown updates and is not GPL 🎉 

I will be archiving this repo and encouraging folks to head over there instead.
