### ISSUE TITLE
Unknown tag 'svg' 

### ISSUE THREAD

**Issue by stoplion** [andrewmcodes/bridgetown-inline-svg#7]
## What did you do?
`gem "bridgetown-inline-svg", "~> 1.1", :group => :bridgetown_plugin`

```
    // in liquid file
    {% svg 'assets/down-arrow.svg' %}
```
## What did you expect to happen?
SVG to show up

## What actually happened?
```
 Liquid Exception: Liquid syntax error (line 4): Unknown tag 'svg' in /Users/me/Code/project/src/_layouts/default.erb
```

## Environment

**Ruby Version:**
ruby 2.6.3p62

**Framework Version (Rails, whatever):**
gem "bridgetown", "~> 0.16"

**Dev Api Version:**

**Comment by andrewmcodes** [comment]
@stoplion Maybe you need to restart the project? 

Are you trying to use it in an erb file? 

Will need a reproduction to really help.

**Comment by stoplion** [comment]
Sure! Here is a link the branch with the SVG added
https://github.com/stoplion/georgenorr.is/pull/1

**Comment by george-norris-salesforce** [comment]
Was a copy pasta issue.. `bridgetown_plugins` not `bridgetown_plugin` 🤦  closing!

**Comment by stoplion** [comment]
Was a copy pasta issue.. `bridgetown_plugins` not `bridgetown_plugin` 🤦  can close!
